name: generate animation

on:
  schedule:
    - cron: "0 */24 * * *" 
  push:
    branches:
    - main
  workflow_dispatch:
    
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: generate github-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#FF6E96
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#FF6E96

      - name: push github-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
